### Titulo
lorem

In [1]:
# Imports & paths

import pandas as pd
import numpy as np

# Paths

processed = '../data/processed/happiness_complete.csv'

# Define

pd.set_option('display.max_rows', 1000)
pd.set_option('display.precision', 2)

In [2]:
# Extract & Exploration

df = pd.read_csv(processed, low_memory=False)
df_copy = df.copy()

## Analysis

In [3]:
# Separating the years

df_2015 = df_copy[df_copy['Year'] == 2015]
df_2016 = df_copy[df_copy['Year'] == 2016]
df_2017 = df_copy[df_copy['Year'] == 2017]
df_2018 = df_copy[df_copy['Year'] == 2018]
df_2019 = df_copy[df_copy['Year'] == 2019]

## Top 10

In [4]:
# Top 10 most happiness countries by years

print(f"\nTop 10 most happiness countries by years")
most_happines = df_copy.groupby('Country')['Happiness Score'].mean().sort_values(ascending=False).head(10)
display(most_happines.to_frame().style.format(precision=2)) 

# Top 10 less happiness countries by years

print(f"\nTop 10 less happiness countries by years")
less_happines = df_copy.groupby('Country')['Happiness Score'].mean().sort_values(ascending=True).head(10)
display(less_happines.to_frame().style.format(precision=2))

Top 10 most happiness countries by years

Top 10 less happiness countries by years

## Wealth vs Happiness

In [5]:
# Wealth Vs Happiness

print(f"\n10 most")
happinessXeconomy = df_copy.groupby('Happiness Score')['Economy (GDP)'].mean().sort_values(ascending=False)
display(happinessXeconomy.to_frame().head(10))

print(f"\n10 less")
happinessXeconomy = df_copy.groupby('Happiness Score')['Economy (GDP)'].mean().sort_values(ascending=True)
display(happinessXeconomy.to_frame().head(10))

10 most

                 Economy (GDP)
Happiness Score
6.77                      2.10
6.86                      1.74
6.38                      1.70
6.87                      1.70
6.57                      1.69
6.61                      1.69
6.37                      1.67
6.74                      1.65
6.11                      1.63
6.65                      1.63

10 less

                 Economy (GDP)
Happiness Score
2.69                      0.00
5.44                      0.00
4.98                      0.00
4.52                      0.00
4.67                      0.00
4.29                      0.02
5.15                      0.02
3.08                      0.03
3.77                      0.05
4.27                      0.06

## Health

In [6]:
correlation = df_copy[['Happiness Score', 'Economy (GDP)', 'Health']].corr()
display(correlation.style.background_gradient(cmap='coolwarm').format(precision=2))

## Growth Happiness

In [7]:
total_happines2015 = (df_2015['Happiness Score'].sum())/158
total_happines2016 = (df_2016['Happiness Score'].sum())/157
total_happines2017 = (df_2017['Happiness Score'].sum())/155
total_happines2018 = (df_2018['Happiness Score'].sum())/156
total_happines2019 = (df_2019['Happiness Score'].sum())/156

print(f"\n{total_happines2015}")
print(f"\n{total_happines2016}")
print(f"\n{total_happines2017}")
print(f"\n{total_happines2018}")
print(f"\n{total_happines2019}")

5.375734177215189

5.382184713375795

5.354019355773926

5.375916666666667

5.407096153846155

## Brazil Happiness

In [8]:
# Brazil Happiness Score sum
value2015 = df.loc[(df['Country'] == 'Brazil') & (df['Year'] == 2015), 'Happiness Score'].values[0]
value2016 = df.loc[(df['Country'] == 'Brazil') & (df['Year'] == 2016), 'Happiness Score'].values[0]
value2017 = df.loc[(df['Country'] == 'Brazil') & (df['Year'] == 2017), 'Happiness Score'].values[0]
value2018 = df.loc[(df['Country'] == 'Brazil') & (df['Year'] == 2018), 'Happiness Score'].values[0]
value2019 = df.loc[(df['Country'] == 'Brazil') & (df['Year'] == 2019), 'Happiness Score'].values[0]

mean = (value2015 + value2016 + value2017 + value2018 + value2019) / 5

## Trust

In [9]:
total_trust2015 = (df_2015['Trust (Government)'].sum())/158
total_trust2016 = (df_2016['Trust (Government)'].sum())/157
total_trust2017 = (df_2017['Trust (Government)'].sum())/155
total_trust2018 = (df_2018['Trust (Government)'].sum())/156
total_trust2019 = (df_2019['Trust (Government)'].sum())/156

print(f"\n{total_trust2015}")
print(f"\n{total_trust2016}")
print(f"\n{total_trust2017}")
print(f"\n{total_trust2018}")
print(f"\n{total_trust2019}")

0.14342183544303796

0.13762375796178342

0.12312022065142951

0.11128205128205128

0.11060256410256411